### ISSUE TITLE
Having trouble saving rolls

### ISSUE THREAD

**Issue by BlazeNinjaDogg** [asellitt/diceulator-fitbit-app#2]
I'm sorry. I can't figure it out. I can enter rolls and use the preset rolls, but my Saved Rolls page does nothing. Is there an FAQ? This is for the Versa 2.

**Comment by asellitt** [comment]
Nah, no FAQ. I'd be happy to accept a PR for one if you're up for it.

Hopefully this helps you:

1. Open the this app in the Fitbit app in your phone (Avatar icon -> device -> Gallery -> Diceulator)
2. Go to Settings
3. Click "+ Add new roll"
4. Add your roll, so say its for Fireball, and it does 8d6 then you'd enter: `Fireball,8d6`
5. Click Save.
6. On you Fitbit, open Diceulator
7. Swipe left
8. Tap on Fireball (or whatever you named the saved roll).

This should prefill the calculator and roll a value.

**Comment by BlazeNinjaDogg** [comment]
Oh my God thank you! That makes perfect sense! I was trying to do it on the
watch not the app. You rock!
